# Generated by Django 5.1.2 on 2024-11-14 18:09

import django.core.validators
import django.db.models.deletion
import domains.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subdomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[domains.validators.validate_subdomain],
                    ),
                ),
                (
                    "A_record",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        validators=[django.core.validators.validate_ipv4_address],
                    ),
                ),
                (
                    "AAAA_record",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        validators=[django.core.validators.validate_ipv6_address],
                    ),
                ),
                ("TXT_record", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="domains.domain"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
