services:
  django:
    env_file: .env
    image: git.06222001.xyz/keannu125/mehdns_backend:latest
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PYTHONBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - postgres
      - pgbouncer

  # Optional PostgreSQL Database
  # postgres:
  #   env_file: .env
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=${DB_DATABASE}
  #     - POSTGRES_USER=${DB_USERNAME}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
