services:
  django:
    env_file: .env
    image: git.06222001.xyz/keannu125/mehdns_backend:latest
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PYTHONBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - postgres
      - pgbouncer

  redis:
    image: redis:latest

volumes:
  db_data:
